# Electric Hunter - the saga (Turkish master copy). Speakers: S = Serhat, O = his son, B = the boss, I = Necmettin's good side
CH = {'ch1': 'Bölüm 1 · Kaçırılış', 'ch2': 'Bölüm 2 · Karanlık Şebeke', 'ch3': 'Bölüm 3 · Kayıp Mahalle', 'ch4': 'Sonsuz Yarık',
      'son': 'Oğlu', 'skip': 'Atla', 'tapNext': 'Devam için dokun', 'storyGo': 'Devam', 'endlessIsl': 'Sonsuz Yarık · Ada {n}',
      'freed': '{name} kurtuldu!', 'freedSub': 'İnsan hâline döndü ve portaldan eve gitti',
      'rescueT': 'Oğlun kurtuldu!', 'kidJoin': 'Oğlun artık yanında: canavarlara kıvılcım atıyor',
      'gridT': 'Dünya\'nın ışıkları yandı!', 'endT': 'Mahalle eve döndü!', 'endSub': 'Sonsuz Yarık açıldı: adalar sonsuza dek sürüyor, her biri daha güçlü',
      'resetNote': 'Yeni hikâye geldi! Herkes Mars\'tan yeniden başlıyor. Jetonların ve satın aldıkların duruyor.'}
# arrival narration, one per island (first visit)
ST = [
 'Portal Serhat\'ı kızıl bir çöle fırlattı. Uzakta bir canavarın sırtındaki kafeste oğlunun ışığı yanıp sönüyor.',
 'Buz kırıklarının arasında yarasa çığlıkları. Bu gezegende tanıdık bir koku var… kan ve kardeşinin parfümü.',
 'Volkanlar yeri titretiyor. Bir ses yankılanıyor: "Baba, buradayım!" Ama sesin önünde biri duruyor: yarığı açan kişi.',
 'Turuncu sisin içinde dev ayak izleri. Yaratıklar kafesi elden ele geçiriyor ve her el tanıdık birine ait.',
 'Asit bulutlarının altında yaratıkların pazarı. Burada her şey satılık, insanlar bile.',
 'Fırtına hiç dinmiyor. Pazarlıkçıların en kurnazı kafesin anahtarını burada saklıyor.',
 'Halkaların gölgesinde kafes atölyesi. Oğlunu taşıyan kafesler burada dövülmüş.',
 'Mavi rüzgârların gezegeni. Bir adam kendi kendisiyle kavga ediyor: yarısı dost, yarısı düşman.',
 'Güneşe en yakın ada. Kafes son kez el değiştirdi; şimdi kaçırıcıların başında.',
 'Buz gibi karanlıkta kabloların uğultusu. Oğlu kabloyu dinliyor: "Bu hat bir şehri besliyor baba."',
 'Mor ormanların altından kalın bir hat geçiyor. Her bekçi devrilince Dünya\'da bir şehir yeniden aydınlanıyor.',
 'Buz gayzerleri kabloları soğutuyor. Bekçilerin yüzleri tanıdık: mahallenin ustaları.',
 'Kızıl güneşin altında ustalar zincirlenmiş. Zülfü onları kabloya bağlamış.',
 'Taşlarla kaplı küçük dünya. Şebeke Yiyen\'in nabzı yerden hissediliyor.',
 'Okyanus dünyasında son ana hat. Dünya\'nın yarısı karanlıkta. Ana şalteri bulmak lazım.',
 'Elmas gezegenin kalbinde Şebeke Yiyen bekliyor. Ana şalter onun göğsünde.',
 'Mahalle boşlukta parça parça dağılmış. Kraliçe herkesi yeniden dönüştürdü. Bu sefer onları sonsuza dek kurtaracaksın.',
 'Ganymede\'nin buzunda bir kardeş bekliyor. Vampir laneti bu sefer bitmeli.',
 'Ters akan buz yanardağları. Kraliçe en hainleri muhafızı yapmış.',
 'Hızla dönen yumurta dünya. Kraliçe\'nin yumurtaları burada; her biri yeni bir canavar.',
 'Güneş burada sıradan bir yıldız. Karanlıkta yalnızca Serhat\'ın kablosu parlıyor.',
 'Başka bir güneşin altında iki ruhlu adam yeniden ikiye bölünmüş.',
 'Kara deliğin kıyısında zaman yavaşlıyor. Abdülkadir amca kapının önünde.',
 'Kovan Dünyası. Kovan Kraliçesi tahtında. Mahallenin son ışığı onun tacında parlıyor.',
]
# bosses: name (proper noun, untranslated), title, intro dialogue, outro dialogue
BOSS = [
 ('Hüseyin', 'Evrim geçirmiş dost',
  [('B', 'Serhat… gel… seni bekliyordum. Kardeşim gibiydin.'), ('S', 'Hüseyin? Sana ne yaptılar?'), ('B', 'Bana güç verdiler! Artık yorulmuyorum, acıkmıyorum… sadece yiyorum!'), ('S', 'Oğlum nerede? Söyle, yoksa seni de yerim.')],
  [('B', 'Serhat… affet… bir an kendimi kaybettim.'), ('B', 'Kafesi kardeşin Fuat\'a verdiler. Buzlu gezegende…'), ('S', 'Fuat mı? O da mı burada?')]),
 ('Fuat', 'Vampir kardeş',
  [('S', 'Fuat! Kardeşim!'), ('B', 'Abi… çok susadım. Uzaylılar beni kaçırdı, damarlarımı boşalttılar.'), ('B', 'Şimdi tek istediğim kan. Senin kanın… tanıdık kokuyor abi.'), ('S', 'Seni buradan çıkaracağım. Önce dişlerini sökmem gerekse bile.')],
  [('B', 'Abi… susuzluk geçti… ama lanet gitmedi.'), ('B', 'Kafesi Zülfü aldı. Bütün bunları o başlattı abi!'), ('S', 'Zülfü… biliyordum.')]),
 ('Zülfü', 'Baştan beri hain',
  [('B', 'Hoş geldin Serhat. Yarığı ben açtım, bilmiyor muydun?'), ('S', 'Neden Zülfü? Aynı mahallede büyüdük!'), ('B', 'Sen hep usta oldun, ben hep çırak. Bana güç teklif ettiler, aldım.'), ('B', 'Oğlun da benim pazarlık kozum.')],
  [('B', 'Bu iş bitmedi Serhat! Daha büyük bir şebekeye bağlandım!'), ('S', 'Kaçıyor! Kafes nerede?'), ('B', 'Amcana sor! Özcan seni hep satmıştı zaten. Hahaha!')]),
 ('Özcan', 'Hain amca',
  [('S', 'Özcan amca? Sen de mi?'), ('B', 'Ben hiç değişmedim yeğenim. Sadece maskemi çıkardım.'), ('B', 'Oğlunun yerini onlara ben söyledim. Karşılığında altın verdiler.'), ('S', 'Altınını da seni de yutacağım.')],
  [('B', 'Dur! Dur! Kafesi Fatih\'e sattım! Asit bulutlarının altında!'), ('S', 'Kendi kanını sattın amca.'), ('B', 'Ticaret bu yeğenim… ticaret.')]),
 ('Fatih', 'Şişko çakal',
  [('B', 'Serhat! Ortağım! Gel bir anlaşma yapalım.'), ('S', 'Oğlumu ver Fatih.'), ('B', 'Dünya yıkılsa umurumda değil. Kim çok verirse onunla iş yaparım.'), ('B', 'Uzaylılar bana Dünya\'nın bütün elektriğini vaat etti! Sen ne verebilirsin?')],
  [('B', 'Tamam tamam! Anahtar Fahri\'de! Onu da satarım, beni bırak!'), ('S', 'Sen herkesi satarsın Fatih.'), ('B', 'Ben iş adamıyım!')]),
 ('Fahri', 'Çakal',
  [('B', 'Anahtar mı? Burada. Fiyatı da senin canın.'), ('S', 'Fahri, bu çocuk senin elinde büyüdü!'), ('B', 'Çocukları severim. Satarken daha çok severim.')],
  [('B', 'Anahtar kırıldı! Kafesi Ahmet yeniden dövecek…'), ('S', 'Ahmet mi? Mahallenin en iyi adamı?'), ('B', 'Artık onların kuklası. Satürn\'ün halkalarında.')]),
 ('Ahmet', 'Beyni ele geçirilmiş',
  [('B', 'Serhat… kaç… bu benim sesim değil… onlar konuşuyor…'), ('S', 'Ahmet? Sen mahallenin en iyi adamıydın!'), ('B', 'BEYNİ ARTIK BİZİM. KAFESLERİ ONUN ELLERİYLE DÖVDÜK. SIRA SENDE.')],
  [('B', 'Kafamdaki sesler sustu… Serhat, beynimi yiyip beni kukla yaptılar.'), ('B', 'Kafesin zayıf yeri elektrik. Ve Necmettin\'e dikkat et, içinde iki kişi var.'), ('S', 'Dinlen Ahmet. Seni de eve götüreceğim.')]),
 ('Necmettin', 'İki ruhlu',
  [('I', 'Serhat! Kaç! Kötü yanım uyandı, onu tutamıyorum!'), ('B', 'Sus zayıf yarım! Bu beden artık benim!'), ('I', 'Onu yen Serhat… ama beni öldürme…'), ('S', 'Dayan Necmettin. İkinizi ayıracağım.')],
  [('I', 'Kötü yanım uyudu… şimdilik.'), ('I', 'Oğlun Abdülkadir amcada. Merkür\'de, güneşin dibinde.'), ('S', 'Son kafes. Geliyorum oğlum.')]),
 ('Abdülkadir', 'Kaçırıcıların başı',
  [('B', 'Demek buraya kadar geldin Serhat. Hepsini yendin.'), ('S', 'Abdülkadir amca… sen herkesin büyüğüydün.'), ('B', 'O yüzden seçtiler beni. Büyükler en iyi yalan söyler.'), ('O', 'Baba! Buradayım!'), ('S', 'Dayan oğlum! Geldim!')],
  [('O', 'Babaaa! Geleceğini biliyordum!'), ('S', 'Bir daha seni bırakmayacağım.'), ('O', 'Baba… neden kaçırdıklarını duydum. Dünya\'nın elektriğini emecekler.'), ('O', 'Zülfü mahallemizden kablo çekiyor. Durdurmalıyız!'), ('S', 'O zaman beraber gidiyoruz. Elektrikçinin oğlu, elektrikçi olur.')]),
 ('Azad', 'Kablo bekçisi',
  [('B', 'Bu… hat… korunuyor…'), ('O', 'Baba, bu Azad abi! Gözleri boş bakıyor.'), ('S', 'Zülfü onu kabloya bağlamış. Hattı koparırsak uyanır.')],
  [('B', 'Serhat? Neredeyim? Kafamda bir uğultu vardı…'), ('O', 'Ankara\'nın ışıkları yandı baba!'), ('S', 'Bir hat gitti. Daha çok var.')]),
 ('Eser', 'Kablo bekçisi',
  [('B', 'Akım… akmalı… durdurma…'), ('S', 'Eser! Benim, Serhat!'), ('O', 'Ona kıvılcımımı atacağım baba!')],
  [('B', 'Oğlum… hayır, senin oğlun… büyümüş.'), ('S', 'Eve git Eser. Portal açık.')]),
 ('Rasim', 'Kablo bekçisi',
  [('B', 'Usta… Serhat… sen de mi bağlandın?'), ('S', 'Hayır Rasim. Ben kesmeye geldim.'), ('B', 'Kesemezsin… kablo canlı…')],
  [('B', 'Kafam açıldı. Zülfü bizi pil gibi kullanıyor Serhat.'), ('O', 'İzmir de aydınlandı!')]),
 ('Hicret Hanım', 'Kablo bekçisi',
  [('B', 'Yaklaşma Serhat. Akım beni güzel yaptı.'), ('O', 'Hicret Hanım, siz böyle değildiniz!'), ('S', 'Uzaylıların güzelliği bu kadar. İçin çürüyor.')],
  [('B', 'Teşekkürler… zincirlerim gevşedi.'), ('B', 'Zeynep okyanusta. Ana hattı o tutuyor.')]),
 ('Zeynep', 'Ana hat bekçisi',
  [('B', 'Bu hat kopmaz Serhat. Dünya\'nın yarısı bu kablodan besleniyor.'), ('S', 'O yüzden koparacağım Zeynep.'), ('O', 'Baba, şalter onun arkasında!')],
  [('B', 'Okyanus… nefes alabiliyorum…'), ('B', 'Zülfü elmas gezegende. Kendini şebekeye kaynaklamış.'), ('S', 'Son bir hat kaldı.')]),
 ('Kara Trafo', 'Zülfü\'nün bekçisi',
  [('B', 'VVVVZZZZ… YABANCI AKIM TESPİT EDİLDİ.'), ('O', 'Baba bu bir makine! Uzaylı trafo!'), ('S', 'Trafoyu ben söker takarım. Bu da trafo.')],
  [('B', 'AKIM… KESİLDİ…'), ('O', 'Şebeke Yiyen\'in kalbi bir sonraki adada!')]),
 ('Zülfü', 'Şebeke Yiyen',
  [('B', 'Bak bana Serhat! Artık ben şebekenin kendisiyim!'), ('B', 'Dünya\'nın bütün ışıkları benim damarlarımda akıyor!'), ('S', 'Ben de ana şalteri indirmeye geldim Zülfü.'), ('O', 'Baba, göğsündeki şalter!')],
  [('B', 'Hayııır! Akımım… kaçıyor…'), ('O', 'Baba, bütün şehirler aydınlandı!'), ('S', 'Bitti mi?'), ('O', 'Baba… yarık yeniden açılıyor! Mahalle… mahalle havaya kalkıyor!'), ('S', 'Kovan Kraliçesi. Mahalleyi kaçırıyor!')]),
 ('Hüseyin', 'Kraliçenin askeri',
  [('B', 'Serhat… Kraliçe beni yeniden çağırdı… karşı koyamıyorum.'), ('S', 'Bu sefer seni tamamen kurtaracağım dostum.'), ('O', 'Hüseyin amca, dayan!')],
  [('B', 'Ses kesildi… kafamda kimse yok. Özgürüm!'), ('S', 'Eve git dostum. Çayı ben ısmarlıyorum.')]),
 ('Fuat', 'Vampir kardeş',
  [('B', 'Abi… Kraliçe susuzluğumu geri verdi…'), ('S', 'Bu laneti bugün bitiriyoruz kardeşim.'), ('O', 'Fuat amca, babam seni kurtaracak!')],
  [('B', 'Güneşi hissediyorum abi… dişlerim gitti!'), ('S', 'Hoş geldin kardeşim.')]),
 ('Özcan', 'Kraliçenin muhafızı',
  [('B', 'Yeğenim! Kraliçe bana saray verdi!'), ('S', 'Sen yine satıldın amca.'), ('B', 'En yüksek teklifi o verdi!')],
  [('B', 'Tamam… tamam… eve dönmek istiyorum.'), ('S', 'Dön amca. Ama mahalle seni unutmayacak.')]),
 ('Fatih', 'Yumurta tüccarı',
  [('B', 'Serhat! Kraliçenin yumurtalarını satıyorum, tanesi bir şehir!'), ('O', 'Baba, bu adam hiç değişmiyor.'), ('S', 'Dükkanı kapatıyoruz Fatih.')],
  [('B', 'Peki peki… iflas ettim. Beni de eve götürün.'), ('S', 'Portal herkese açık Fatih. Senin gibilere bile.')]),
 ('Fahri', 'Karanlığın çakalı',
  [('B', 'Bu karanlıkta kimse seni bulamaz Serhat. Seni satsam kimse duymaz.'), ('O', 'Ben görüyorum Fahri amca. Babam parlıyor.'), ('S', 'Kablom karanlıkta da yanar.')],
  [('B', 'Işık… gözüm… tamam, teslim oluyorum.'), ('S', 'Eve git ve bir daha kimseyi satma.')]),
 ('Necmettin', 'İki ruhlu',
  [('I', 'Serhat, yine ikiye bölündüm!'), ('B', 'Bu sefer iyi yarını tamamen yiyeceğim!'), ('S', 'İkinizi birleştirmeye geldim. Ama kötü olan küçülecek.')],
  [('I', 'Tek bir sesim var artık. Kendi sesim.'), ('I', 'Abdülkadir amca Kraliçe\'nin kapısında. Onu da kurtar.')]),
 ('Abdülkadir', 'Kapının bekçisi',
  [('B', 'Serhat… beni bu sefer Kraliçe zorladı.'), ('B', 'Kapıyı açarsam bütün mahalle ölür, açmazsam ben ölürüm.'), ('S', 'Kimse ölmeyecek amca. Ben açarım.')],
  [('B', 'Kapı açıldı. Kraliçe seni bekliyor.'), ('O', 'Baba, sonuna geldik.'), ('S', 'Beraber geldik, beraber döneceğiz.')]),
 ('Kovan Kraliçesi', 'Yarığın sahibi',
  [('B', 'Küçük elektrikçi. Bütün çocuklarımı yedin.'), ('B', 'Şimdi senin mahallen benim kovanım olacak.'), ('O', 'Baba! Mahallenin ışığı onun tacında!'), ('S', 'O ışığı ben yaktım Kraliçe. Geri alıyorum.')],
  [('B', 'Akımın… bu kadar güçlü olamaz…'), ('O', 'Baba! Taç söndü! Herkes uyanıyor!'), ('S', 'Hadi oğlum. Eve gidiyoruz.'), ('O', 'Baba… yarık kapanmadı. Derinlerden bir şey bakıyor.'), ('S', 'Bakarsa baksın. Elektrikçi her zaman nöbette.')]),
]
