// Bundles src/engine.mjs + src/api.mjs into public/_worker.js (Cloudflare Pages advanced mode)
// and copies the engine for the browser.
import {readFileSync, writeFileSync} from 'node:fs';
const root = new URL('..', import.meta.url);
const engine = readFileSync(new URL('src/engine.mjs', root), 'utf8');
const api = readFileSync(new URL('src/api.mjs', root), 'utf8').replace(/^import \{[^}]+\} from '\.\/engine\.mjs';\n/m, '');
writeFileSync(new URL('public/_worker.js', root), '// Generated by scripts/build.mjs — edit src/ instead.\n' + engine + '\n' + api);
writeFileSync(new URL('public/engine.js', root), '// Generated by scripts/build.mjs — edit src/engine.mjs instead.\n' + engine);
console.log('built public/_worker.js and public/engine.js');
