// Bundles src/engine.mjs + src/api.mjs into public/_worker.js (Cloudflare Pages advanced mode),
// copies the engine for the browser, and embeds the localized login e-mail + delete-confirm words
// from public/i18n/*.json.
import {readFileSync, writeFileSync, readdirSync} from 'node:fs';
const root = new URL('..', import.meta.url);
const engine = readFileSync(new URL('src/engine.mjs', root), 'utf8');
const api = readFileSync(new URL('src/api.mjs', root), 'utf8').replace(/^import \{[^}]+\} from '\.\/(engine|pay)\.mjs';\r?\n/gm, '');
const pay = readFileSync(new URL('src/pay.mjs', root), 'utf8');
const mail = {}, del = new Set(['SIL', 'DELETE']);
for (const f of readdirSync(new URL('public/i18n/', root)).filter(f => f.endsWith('.json'))){
  const j = JSON.parse(readFileSync(new URL('public/i18n/' + f, root), 'utf8'));
  mail[f.slice(0, -5)] = {subject: j.mailSubject, body: j.mailBody};
  if (j.delWord) del.add(j.delWord);
}
const data = `globalThis.__EM_MAIL__ = ${JSON.stringify(mail)};\nglobalThis.__EM_DEL_WORDS__ = ${JSON.stringify([...del])};\n`;
writeFileSync(new URL('public/_worker.js', root), '// Generated by scripts/build.mjs — edit src/ instead.\n' + data + engine + '\n' + pay + '\n' + api);
writeFileSync(new URL('public/engine.js', root), '// Generated by scripts/build.mjs — edit src/engine.mjs instead.\n' + engine);
console.log('built public/_worker.js and public/engine.js (' + Object.keys(mail).length + ' languages)');
